# Generated by Django 3.0.2 on 2020-01-25 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('job_rate', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.SmallIntegerField(blank=True, null=True)),
                ('job_status', models.SmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_message', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'job_log',
                'managed': False,
            },
        ),
    ]
