# Generated by Django 3.0.2 on 2020-01-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpReview',
            fields=[
                ('review_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('business_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=5000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yelp_review',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='YelpScraping',
        ),
    ]
